apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app05
  labels:
    app: todo-app05
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app05
  template:
    metadata:
      labels:
        app: todo-app05
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: todo-app99
        image: 183071452060.dkr.ecr.ap-northeast-2.amazonaws.com/todo-app05:38cc6ab
        ports:
        - containerPort: 5000